# Generated by Django 5.0.4 on 2024-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default='5000'),
            preserve_default=False,
        ),
    ]
